F0112 23:07:59.588449  7175  7175 raylet_client.cc:57] Could not connect to socket /tmp/pminervi-7175-ray/session_2021-01-12_23-05-09_476469_7175/sockets/raylet
*** Check failure stack trace: ***
    @     0x2b6f70f9910d  google::LogMessage::Fail()
    @     0x2b6f70f9a57c  google::LogMessage::SendToLog()
    @     0x2b6f70f98de9  google::LogMessage::Flush()
    @     0x2b6f70f99001  google::LogMessage::~LogMessage()
    @     0x2b6f70f4c479  ray::RayLog::~RayLog()
    @     0x2b6f70c678bf  ray::raylet::RayletConnection::RayletConnection()
    @     0x2b6f70c68bd0  ray::raylet::RayletClient::RayletClient()
    @     0x2b6f70c0c12b  ray::CoreWorker::CoreWorker()
    @     0x2b6f70c0fce4  ray::CoreWorkerProcess::CreateWorker()
    @     0x2b6f70c10f52  ray::CoreWorkerProcess::CoreWorkerProcess()
    @     0x2b6f70c1192b  ray::CoreWorkerProcess::Initialize()
    @     0x2b6f70b41de6  __pyx_pw_3ray_7_raylet_10CoreWorker_1__cinit__()
    @     0x2b6f70b43595  __pyx_tp_new_3ray_7_raylet_CoreWorker()
    @     0x56383578b715  type_call
    @     0x56383570492b  _PyObject_FastCallDict
    @     0x56383578b57e  call_function
    @     0x5638357b038a  _PyEval_EvalFrameDefault
    @     0x563835784bfe  _PyEval_EvalCodeWithName
    @     0x563835785771  fast_function
    @     0x56383578b505  call_function
    @     0x5638357b1147  _PyEval_EvalFrameDefault
    @     0x5638357868c6  PyEval_EvalCodeEx
    @     0x5638357871a6  function_call
    @     0x56383570454e  PyObject_Call
    @     0x5638357b1a6c  _PyEval_EvalFrameDefault
    @     0x56383578553b  fast_function
    @     0x56383578b505  call_function
    @     0x5638357b038a  _PyEval_EvalFrameDefault
    @     0x563835786289  PyEval_EvalCodeEx
    @     0x56383578701c  PyEval_EvalCode
    @     0x5638358093c4  run_mod
    @     0x5638358097c1  PyRun_FileExFlags
